name: update stars

on:
  push:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: update
        env: 
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          REPO_NAME: ${{ github.repository }}
        run: hub api "repos/$REPO_NAME" --raw-field "name=this-repo-has-$(curl -s https://api.github.com/repos/$REPO_NAME | jq '.stargazers_count')-stars" > /dev/null

